added slider for the mouse sensitivity
Team-Swamp/The-Lost-Reel pull request #27
Opened 2023-08-12 12:23 UTC by rickdohmen

2023-08-13 14:46 UTC, Tatum13 submitted a review, later dismissed

2023-08-13 14:46 UTC, Tatum13 commented on Assets/Scripts/Player/Movement/CameraController.cs
> +    [field: SerializeField]public float mouseSensitivity { get; set; } = 250.0f;
```suggestion
    [field: SerializeField] public float mouseSensitivity { get; set; } = 250.0f;
```

2023-08-13 14:46 UTC, Tatum13 commented on Assets/Scripts/UI/Menu's/VolumeSlider.cs
> +        AudioListener.volume = volumeSlider.value;
Je kan hier de audiosource aanroepen

2023-08-14 00:40 UTC, Tatum13 commented on Assets/Scripts/UI/Menu's/VolumeSlider.cs
> +        float volumeValue = PlayerPrefs.GetFloat("VolumeValue");
```suggestion
        var volumeValue = PlayerPrefs.GetFloat("VolumeValue");
```

2023-08-14 00:42 UTC, Tatum13 approved these changes

2023-08-14 00:50 UTC, bas-boop requested changes

2023-08-14 00:50 UTC, bas-boop commented on Assets/Scripts/UI/Menu's/MousSensitivity.cs
> +    }
```suggestion
    private void ChangeSensitivity(float newSensitivity) => cameraController.mouseSensitivity = newSensitivity;
```

2023-08-14 00:50 UTC, bas-boop commented on Assets/Scripts/UI/Menu's/VolumeSlider.cs
> +    }
```suggestion
    public void VolumeSliderController(float volume) => volumeTextUI.text = volume.ToString("100.0");
```

2023-08-14 00:52 UTC, bas-boop approved these changes

2023-08-14 00:57 UTC, merged